services:
  - type: web
    name: telegram-personalities-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: TELEGRAM_TOKEN
        value: ""
        fromSecret: false
      - key: OPENAI_API_KEY
        value: ""
        fromSecret: false
      - key: DATABASE_PATH
        value: "data.db"
      - key: ADMIN_IDS
        value: "761662415"
